### ISSUE TITLE
Tweeting this tomorrow

### ISSUE THREAD

**Issue by soumith** [mrkulk/NeuralPartialProgramSynthesis#1]
Hey, tweeting this tomorrow from the TorchML account. You might want to update the readme and make it a bit more detailed.

**Comment by soumith** [comment]
tweeted your capsule networks implementation today.

**Comment by soumith** [comment]
If it's not ready for public consumption, let me know asap.

**Comment by mrkulk** [comment]
Hi @soumith 

I have to update the implementation due to several known issues. I will put a disclaimer on the README for now. 

As for the capsules implementation -- thanks a lot! I appreciate it. I think that should be consumable.

**Comment by soumith** [comment]
ok cool. i'll hold off for now then. do let me know when it's ready, would love to see it get visibility.

**Comment by mrkulk** [comment]
definitely! thanks a lot
